apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-hello
spec:
  rules:
    - host: foo.bar.com
      http:
        paths:
          - path: /helloworld
            pathType: Prefix
            backend:
              service:
                name: jboss-helloworld-service
                port:
                  number: 8080
